spring.application.name=Church

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/churchdb
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

jwt.secret=8A3B8C2D5F8E2A4B6C9D3F1A4E7B2D5C8F1A3B6D9E2C4F7A1B3D5E8C2F4A6B9D

# Increase multipart file upload size limits to 50MB
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Twilio Configuration
twilio.enabled=true
twilio.account-sid=AC9b4e52b89b4eddd2ccee036ac6846bb5
twilio.auth-token=f6e5052c996abadd3fd74b26beaf0a00
twilio.from-whatsapp-number=whatsapp:+14155238886
twilio.from-sms-number=+14155238886
twilio.content-sid=HXb5b62575e6e4ff6129ad7c8efe1f983e

# Spring Mail Properties (Simulation/Mock mode when left empty)
spring.mail.host=
spring.mail.port=587
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
